/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkflowRouteImport } from './routes/_authenticated.workflow'
import { Route as AuthenticatedIotRouteImport } from './routes/_authenticated.iot'
import { Route as AuthenticatedGisRouteImport } from './routes/_authenticated.gis'
import { Route as AuthenticatedBimRouteImport } from './routes/_authenticated.bim'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkflowRoute = AuthenticatedWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIotRoute = AuthenticatedIotRouteImport.update({
  id: '/iot',
  path: '/iot',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGisRoute = AuthenticatedGisRouteImport.update({
  id: '/gis',
  path: '/gis',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBimRoute = AuthenticatedBimRouteImport.update({
  id: '/bim',
  path: '/bim',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bim': typeof AuthenticatedBimRoute
  '/gis': typeof AuthenticatedGisRoute
  '/iot': typeof AuthenticatedIotRoute
  '/workflow': typeof AuthenticatedWorkflowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bim': typeof AuthenticatedBimRoute
  '/gis': typeof AuthenticatedGisRoute
  '/iot': typeof AuthenticatedIotRoute
  '/workflow': typeof AuthenticatedWorkflowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/bim': typeof AuthenticatedBimRoute
  '/_authenticated/gis': typeof AuthenticatedGisRoute
  '/_authenticated/iot': typeof AuthenticatedIotRoute
  '/_authenticated/workflow': typeof AuthenticatedWorkflowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/admin' | '/bim' | '/gis' | '/iot' | '/workflow'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/admin' | '/bim' | '/gis' | '/iot' | '/workflow'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/bim'
    | '/_authenticated/gis'
    | '/_authenticated/iot'
    | '/_authenticated/workflow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workflow': {
      id: '/_authenticated/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof AuthenticatedWorkflowRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/iot': {
      id: '/_authenticated/iot'
      path: '/iot'
      fullPath: '/iot'
      preLoaderRoute: typeof AuthenticatedIotRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gis': {
      id: '/_authenticated/gis'
      path: '/gis'
      fullPath: '/gis'
      preLoaderRoute: typeof AuthenticatedGisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bim': {
      id: '/_authenticated/bim'
      path: '/bim'
      fullPath: '/bim'
      preLoaderRoute: typeof AuthenticatedBimRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBimRoute: typeof AuthenticatedBimRoute
  AuthenticatedGisRoute: typeof AuthenticatedGisRoute
  AuthenticatedIotRoute: typeof AuthenticatedIotRoute
  AuthenticatedWorkflowRoute: typeof AuthenticatedWorkflowRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBimRoute: AuthenticatedBimRoute,
  AuthenticatedGisRoute: AuthenticatedGisRoute,
  AuthenticatedIotRoute: AuthenticatedIotRoute,
  AuthenticatedWorkflowRoute: AuthenticatedWorkflowRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
