/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as ProjectsProjectIdStandardRouteImport } from './routes/projects/$projectId/standard'
import { Route as ProjectsProjectIdSettingsRouteImport } from './routes/projects/$projectId/settings'
import { Route as ProjectsProjectIdModelRouteImport } from './routes/projects/$projectId/model'
import { Route as ProjectsProjectIdDocumentsRouteImport } from './routes/projects/$projectId/documents'
import { Route as ProjectsProjectIdClashesRouteImport } from './routes/projects/$projectId/clashes'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdStandardRoute =
  ProjectsProjectIdStandardRouteImport.update({
    id: '/standard',
    path: '/standard',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdSettingsRoute =
  ProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdModelRoute = ProjectsProjectIdModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdDocumentsRoute =
  ProjectsProjectIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdClashesRoute =
  ProjectsProjectIdClashesRouteImport.update({
    id: '/clashes',
    path: '/clashes',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/clashes': typeof ProjectsProjectIdClashesRoute
  '/projects/$projectId/documents': typeof ProjectsProjectIdDocumentsRoute
  '/projects/$projectId/model': typeof ProjectsProjectIdModelRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/standard': typeof ProjectsProjectIdStandardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/clashes': typeof ProjectsProjectIdClashesRoute
  '/projects/$projectId/documents': typeof ProjectsProjectIdDocumentsRoute
  '/projects/$projectId/model': typeof ProjectsProjectIdModelRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/standard': typeof ProjectsProjectIdStandardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/clashes': typeof ProjectsProjectIdClashesRoute
  '/projects/$projectId/documents': typeof ProjectsProjectIdDocumentsRoute
  '/projects/$projectId/model': typeof ProjectsProjectIdModelRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/standard': typeof ProjectsProjectIdStandardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/projects/$projectId'
    | '/projects/'
    | '/projects/$projectId/clashes'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/model'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/standard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects/$projectId'
    | '/projects'
    | '/projects/$projectId/clashes'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/model'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/standard'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/projects/$projectId'
    | '/projects/'
    | '/projects/$projectId/clashes'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/model'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/standard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId/standard': {
      id: '/projects/$projectId/standard'
      path: '/standard'
      fullPath: '/projects/$projectId/standard'
      preLoaderRoute: typeof ProjectsProjectIdStandardRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/settings': {
      id: '/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ProjectsProjectIdSettingsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/model': {
      id: '/projects/$projectId/model'
      path: '/model'
      fullPath: '/projects/$projectId/model'
      preLoaderRoute: typeof ProjectsProjectIdModelRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/documents': {
      id: '/projects/$projectId/documents'
      path: '/documents'
      fullPath: '/projects/$projectId/documents'
      preLoaderRoute: typeof ProjectsProjectIdDocumentsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/clashes': {
      id: '/projects/$projectId/clashes'
      path: '/clashes'
      fullPath: '/projects/$projectId/clashes'
      preLoaderRoute: typeof ProjectsProjectIdClashesRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdClashesRoute: typeof ProjectsProjectIdClashesRoute
  ProjectsProjectIdDocumentsRoute: typeof ProjectsProjectIdDocumentsRoute
  ProjectsProjectIdModelRoute: typeof ProjectsProjectIdModelRoute
  ProjectsProjectIdSettingsRoute: typeof ProjectsProjectIdSettingsRoute
  ProjectsProjectIdStandardRoute: typeof ProjectsProjectIdStandardRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdClashesRoute: ProjectsProjectIdClashesRoute,
  ProjectsProjectIdDocumentsRoute: ProjectsProjectIdDocumentsRoute,
  ProjectsProjectIdModelRoute: ProjectsProjectIdModelRoute,
  ProjectsProjectIdSettingsRoute: ProjectsProjectIdSettingsRoute,
  ProjectsProjectIdStandardRoute: ProjectsProjectIdStandardRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
