/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as HubSettingsRouteImport } from './routes/hub-settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ArProjectIdRouteImport } from './routes/ar.$projectId'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as ProjectsProjectIdClashesRouteImport } from './routes/projects/$projectId/clashes'
import { Route as ProjectsProjectIdDocumentsRouteImport } from './routes/projects/$projectId/documents'
import { Route as ProjectsProjectIdDrawingRouteImport } from './routes/projects/$projectId/drawing'
import { Route as ProjectsProjectIdModelRouteImport } from './routes/projects/$projectId/model'
import { Route as ProjectsProjectIdPowerbiRouteImport } from './routes/projects/$projectId/powerbi'
import { Route as ProjectsProjectIdSettingsRouteImport } from './routes/projects/$projectId/settings'
import { Route as ProjectsProjectIdStandardRouteImport } from './routes/projects/$projectId/standard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const HubSettingsRoute = HubSettingsRouteImport.update({
  id: '/hub-settings',
  path: '/hub-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ArProjectIdRoute = ArProjectIdRouteImport.update({
  id: '/ar/$projectId',
  path: '/ar/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdClashesRoute =
  ProjectsProjectIdClashesRouteImport.update({
    id: '/clashes',
    path: '/clashes',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdDocumentsRoute =
  ProjectsProjectIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdDrawingRoute =
  ProjectsProjectIdDrawingRouteImport.update({
    id: '/drawing',
    path: '/drawing',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdModelRoute = ProjectsProjectIdModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdPowerbiRoute =
  ProjectsProjectIdPowerbiRouteImport.update({
    id: '/powerbi',
    path: '/powerbi',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdSettingsRoute =
  ProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdStandardRoute =
  ProjectsProjectIdStandardRouteImport.update({
    id: '/standard',
    path: '/standard',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/hub-settings': typeof HubSettingsRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/ar/$projectId': typeof ArProjectIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/clashes': typeof ProjectsProjectIdClashesRoute
  '/projects/$projectId/documents': typeof ProjectsProjectIdDocumentsRoute
  '/projects/$projectId/drawing': typeof ProjectsProjectIdDrawingRoute
  '/projects/$projectId/model': typeof ProjectsProjectIdModelRoute
  '/projects/$projectId/powerbi': typeof ProjectsProjectIdPowerbiRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/standard': typeof ProjectsProjectIdStandardRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/hub-settings': typeof HubSettingsRoute
  '/login': typeof LoginRoute
  '/ar/$projectId': typeof ArProjectIdRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/clashes': typeof ProjectsProjectIdClashesRoute
  '/projects/$projectId/documents': typeof ProjectsProjectIdDocumentsRoute
  '/projects/$projectId/drawing': typeof ProjectsProjectIdDrawingRoute
  '/projects/$projectId/model': typeof ProjectsProjectIdModelRoute
  '/projects/$projectId/powerbi': typeof ProjectsProjectIdPowerbiRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/standard': typeof ProjectsProjectIdStandardRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/hub-settings': typeof HubSettingsRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/ar/$projectId': typeof ArProjectIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/clashes': typeof ProjectsProjectIdClashesRoute
  '/projects/$projectId/documents': typeof ProjectsProjectIdDocumentsRoute
  '/projects/$projectId/drawing': typeof ProjectsProjectIdDrawingRoute
  '/projects/$projectId/model': typeof ProjectsProjectIdModelRoute
  '/projects/$projectId/powerbi': typeof ProjectsProjectIdPowerbiRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/standard': typeof ProjectsProjectIdStandardRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/hub-settings'
    | '/login'
    | '/projects'
    | '/ar/$projectId'
    | '/projects/$projectId'
    | '/projects/'
    | '/projects/$projectId/clashes'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/drawing'
    | '/projects/$projectId/model'
    | '/projects/$projectId/powerbi'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/standard'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/hub-settings'
    | '/login'
    | '/ar/$projectId'
    | '/projects'
    | '/projects/$projectId/clashes'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/drawing'
    | '/projects/$projectId/model'
    | '/projects/$projectId/powerbi'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/standard'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/hub-settings'
    | '/login'
    | '/projects'
    | '/ar/$projectId'
    | '/projects/$projectId'
    | '/projects/'
    | '/projects/$projectId/clashes'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/drawing'
    | '/projects/$projectId/model'
    | '/projects/$projectId/powerbi'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/standard'
    | '/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  HubSettingsRoute: typeof HubSettingsRoute
  LoginRoute: typeof LoginRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ArProjectIdRoute: typeof ArProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub-settings': {
      id: '/hub-settings'
      path: '/hub-settings'
      fullPath: '/hub-settings'
      preLoaderRoute: typeof HubSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/$projectId': {
      id: '/ar/$projectId'
      path: '/ar/$projectId'
      fullPath: '/ar/$projectId'
      preLoaderRoute: typeof ArProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/clashes': {
      id: '/projects/$projectId/clashes'
      path: '/clashes'
      fullPath: '/projects/$projectId/clashes'
      preLoaderRoute: typeof ProjectsProjectIdClashesRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/documents': {
      id: '/projects/$projectId/documents'
      path: '/documents'
      fullPath: '/projects/$projectId/documents'
      preLoaderRoute: typeof ProjectsProjectIdDocumentsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/drawing': {
      id: '/projects/$projectId/drawing'
      path: '/drawing'
      fullPath: '/projects/$projectId/drawing'
      preLoaderRoute: typeof ProjectsProjectIdDrawingRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/model': {
      id: '/projects/$projectId/model'
      path: '/model'
      fullPath: '/projects/$projectId/model'
      preLoaderRoute: typeof ProjectsProjectIdModelRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/powerbi': {
      id: '/projects/$projectId/powerbi'
      path: '/powerbi'
      fullPath: '/projects/$projectId/powerbi'
      preLoaderRoute: typeof ProjectsProjectIdPowerbiRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/settings': {
      id: '/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ProjectsProjectIdSettingsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/standard': {
      id: '/projects/$projectId/standard'
      path: '/standard'
      fullPath: '/projects/$projectId/standard'
      preLoaderRoute: typeof ProjectsProjectIdStandardRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdClashesRoute: typeof ProjectsProjectIdClashesRoute
  ProjectsProjectIdDocumentsRoute: typeof ProjectsProjectIdDocumentsRoute
  ProjectsProjectIdDrawingRoute: typeof ProjectsProjectIdDrawingRoute
  ProjectsProjectIdModelRoute: typeof ProjectsProjectIdModelRoute
  ProjectsProjectIdPowerbiRoute: typeof ProjectsProjectIdPowerbiRoute
  ProjectsProjectIdSettingsRoute: typeof ProjectsProjectIdSettingsRoute
  ProjectsProjectIdStandardRoute: typeof ProjectsProjectIdStandardRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdClashesRoute: ProjectsProjectIdClashesRoute,
  ProjectsProjectIdDocumentsRoute: ProjectsProjectIdDocumentsRoute,
  ProjectsProjectIdDrawingRoute: ProjectsProjectIdDrawingRoute,
  ProjectsProjectIdModelRoute: ProjectsProjectIdModelRoute,
  ProjectsProjectIdPowerbiRoute: ProjectsProjectIdPowerbiRoute,
  ProjectsProjectIdSettingsRoute: ProjectsProjectIdSettingsRoute,
  ProjectsProjectIdStandardRoute: ProjectsProjectIdStandardRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  HubSettingsRoute: HubSettingsRoute,
  LoginRoute: LoginRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ArProjectIdRoute: ArProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
