import { createRouter } from '@tanstack/react-router'
import { routeTree } from './routeTree.gen'
import { queryClient } from '@/lib/queryClient'

// ─── Router Instance ──────────────────────────────────────────────────────────
// The routeTree is auto-generated by the TanStack Router Vite plugin
// from the files in src/routes/. Never edit routeTree.gen.ts manually.
export const router = createRouter({
  routeTree,
  // Pass queryClient as router context so route loaders can use it
  context: {
    queryClient,
  },
  defaultPreload: 'intent',
  defaultPreloadStaleTime: 0,
})

// ─── Type Registration ─────────────────────────────────────────────────────────
// This enables type-safe useParams, useSearch, Link, etc. across the app
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}
